// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLfVXGRthUWwO8hcO2yBqQkzBNeKOYG0M',
    appId: '1:1063391873873:web:b8e1d45d492c68d3712170',
    messagingSenderId: '1063391873873',
    projectId: 'fabioftth-firebase-app',
    authDomain: 'fabioftth-firebase-app.firebaseapp.com',
    storageBucket: 'fabioftth-firebase-app.appspot.com',
    measurementId: 'G-JWYZZNZYBC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCevrr7yuA6d-scvdS6_zSCVi3C6FRsiCk',
    appId: '1:1063391873873:android:62c32d1360cf4664712170',
    messagingSenderId: '1063391873873',
    projectId: 'fabioftth-firebase-app',
    storageBucket: 'fabioftth-firebase-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOJ1UDh2nJ47ECLpglDepo_Dcq6I98VHQ',
    appId: '1:1063391873873:ios:d2cac0b69b7bc388712170',
    messagingSenderId: '1063391873873',
    projectId: 'fabioftth-firebase-app',
    storageBucket: 'fabioftth-firebase-app.appspot.com',
    iosBundleId: 'com.josefabio.trilhaapp.trilhaapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOJ1UDh2nJ47ECLpglDepo_Dcq6I98VHQ',
    appId: '1:1063391873873:ios:314bdb3c317a9f73712170',
    messagingSenderId: '1063391873873',
    projectId: 'fabioftth-firebase-app',
    storageBucket: 'fabioftth-firebase-app.appspot.com',
    iosBundleId: 'com.josefabio.trilhaapp.trilhaapp.RunnerTests',
  );
}
